#ifndef _EFFECTS
#define _EFFECTS
#include "attributes.h"
const enum class EFFECTS : const short {
	EFF_ARMOR,
	EFF_DEC_ARMOR,
	EFF_DAMAGE,
	EFF_DEC_DAMAGE,
	EFF_REGENERATION_H,
	EFF_REGENERATION_M,
	EFF_DEC_REGENERATION_H,
	EFF_DEC_REGENERATION_M,
	EFF_BOOST_H,
	EFF_BOOST_M,
	EFF_DEC_HEAL,
	EFF_DEC_HEAL_MANA,
	EFF_DEC_SPEED,
	EFF_DEC_CRIT_DMG,
	EFF_DEC_CRIT_CHANCE,
	EFF_POISON,
	EFF_FREEZE,
	EFF_FIRE,
	EFF_LIGHTNING,
	EFF_SIZE_T
};
#endif